server:
  port: 8080

spring:
  application:
    name: syswatch

  websocket:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO

syswatch:
  ssh:
    host: ${SSH_HOST}
    port: ${SSH_PORT}
    username: ${SSH_USERNAME}
    password: ${SSH_PASSWORD}

prometheus:
  reload-url: ${PROM_RELOAD_URL}
  rule-dir: ${PROM_RULE_DIR}

alert:
  feishu:
    webhook: ${FEISHU_WEBHOOK}

alertmanager:
  url: ${ALERTMANAGER_URL}
  api-path: ${ALERTMANAGER_API_PATH}
  connect-timeout: ${ALERTMANAGER_CONNECT_TIMEOUT}
  read-timeout: ${ALERTMANAGER_READ_TIMEOUT}